# Generated by Django 3.2.6 on 2021-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='hone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
