# Generated by Django 3.2.6 on 2021-09-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_hone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='hone_number',
            new_name='phone_number',
        ),
    ]
